In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.tree  import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('salaries.csv')
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [2]:
df.isnull().sum()

company                  0
job                      0
degree                   0
salary_more_then_100k    0
dtype: int64

In [3]:
df.describe()

salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [4]:
LB = LabelEncoder()
df['company'] = LB.fit_transform(df['company'])
df['job'] = LB.fit_transform(df['job'])
df['degree'] = LB.fit_transform(df['degree'])

In [5]:
df


company  job  degree  salary_more_then_100k
0         2    2       0                      0
1         2    2       1                      0
2         2    0       0                      1
3         2    0       1                      1
4         2    1       0                      0
5         2    1       1                      1
6         0    2       1                      0
7         0    1       0                      0
8         0    0       0                      0
9         0    0       1                      1
10        1    2       0                      1
11        1    2       1                      1
12        1    0       0                      1
13        1    0       1                      1
14        1    1       0                      1
15        1    1       1                      1

In [6]:
X = df.drop(columns =['salary_more_then_100k'])
Y = df['salary_more_then_100k']

In [7]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1)

In [8]:
X_train.shape


(14, 3)

In [9]:
Y_test.shape

(2,)

In [10]:
model_log = LogisticRegression()
model_tree = DecisionTreeClassifier()

In [11]:
model_log.fit(X_train,Y_train)

LogisticRegression()

In [12]:
model_tree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [13]:
model_log.predict(X_test)

array([1, 1], dtype=int64)

In [14]:
model_tree.predict(X_test)

array([0, 1], dtype=int64)

In [15]:
model_log.score(X_train,Y_train)

0.7142857142857143

In [16]:
model_tree.score(X_train,Y_train)

1.0

In [17]:
model_tree_reg = DecisionTreeRegressor()
model_tree_reg.fit(X_train,Y_train)

DecisionTreeRegressor()

In [18]:
model_tree_reg.predict(X_test)


array([0., 1.])

In [19]:
model_tree_reg.score(X_train,Y_train)

1.0